# Generated by Django 4.2.11 on 2024-04-19 10:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('adress', models.CharField(max_length=200)),
                ('passport', models.CharField(max_length=11)),
            ],
        ),
        migrations.CreateModel(
            name='ClientRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('state', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Office',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adress', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateField()),
                ('close_date', models.DateField()),
                ('client_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='adminpanel.client')),
                ('device_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='adminpanel.device')),
                ('office_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='adminpanel.office')),
            ],
        ),
        migrations.AddField(
            model_name='device',
            name='office_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='adminpanel.office'),
        ),
        migrations.AddField(
            model_name='client',
            name='client_role_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='adminpanel.clientrole'),
        ),
    ]
