# Generated by Django 4.2.11 on 2024-04-25 08:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0002_device_type_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='close_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='entry',
            name='create_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
