# Generated by Django 4.2.11 on 2024-04-25 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0003_alter_entry_close_date_alter_entry_create_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='close_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
